#!/usr/bin/env python3
"""Print exact tensor-Bezier point/jet references; never writes files.

Uses Python Fraction and Bernstein polynomials, independently of the Rust
de Boor/derivative-control implementation. Inputs and final outputs are
binary64 bit patterns; all intermediate arithmetic is rational.
"""
from fractions import Fraction as F
import math
import random
import struct


def bits(value):
    return struct.pack(">d", value).hex()


def rounded(value):
    try:
        return float(value)
    except OverflowError:
        return -math.inf if value < 0 else math.inf


def bernstein(degree, index, parameter):
    if not 0 <= index <= degree:
        return F(0)
    return math.comb(degree, index) * parameter**index * (1 - parameter)**(degree - index)


def basis(degree, index, parameter, width, order):
    if order == 0:
        return bernstein(degree, index, parameter)
    if order == 1:
        return degree * (bernstein(degree - 1, index - 1, parameter)
                         - bernstein(degree - 1, index, parameter)) / width
    return degree * (degree - 1) * (
        bernstein(degree - 2, index - 2, parameter)
        - 2 * bernstein(degree - 2, index - 1, parameter)
        + bernstein(degree - 2, index, parameter)
    ) / width**2


def reference(degrees, domains, parameters, controls):
    widths = [F(b) - F(a) for a, b in domains]
    normalized = [(F(t) - F(a)) / width for t, (a, _), width in zip(parameters, domains, widths)]
    homogeneous = []
    for du, dv in [(0, 0), (1, 0), (0, 1), (2, 0), (1, 1), (0, 2)]:
        values = [F(0)] * 4
        for index, control in enumerate(controls):
            i, j = index % (degrees[0] + 1), index // (degrees[0] + 1)
            coefficient = (basis(degrees[0], i, normalized[0], widths[0], du)
                           * basis(degrees[1], j, normalized[1], widths[1], dv))
            weight = F(control[3]) * coefficient
            for axis in range(3):
                values[axis] += F(control[axis]) * weight
            values[3] += weight
        homogeneous.append(values)
    h, hu, hv, huu, huv, hvv = homogeneous
    weight = h[3]
    if not weight:
        return ["pole"]
    point = [value / weight for value in h[:3]]
    u = [(hu[i] - point[i] * hu[3]) / weight for i in range(3)]
    v = [(hv[i] - point[i] * hv[3]) / weight for i in range(3)]
    uu = [(huu[i] - point[i] * huu[3] - 2 * u[i] * hu[3]) / weight for i in range(3)]
    uv = [(huv[i] - point[i] * huv[3] - u[i] * hv[3] - v[i] * hu[3]) / weight for i in range(3)]
    vv = [(hvv[i] - point[i] * hvv[3] - 2 * v[i] * hv[3]) / weight for i in range(3)]
    return [bits(rounded(value)) for values in [point, u, v, uu, uv, vv] for value in values]


def main():
    rng = random.Random(20260920)
    print("# Generated by tools/numerics/generate_surface_rational_reference.py")
    print("# du dv u0 u1 v0 v1 u v; row-major x y z w controls; point du dv duu duv dvv, or pole")
    degree_pairs = [(1, 1), (1, 2), (2, 1), (2, 2), (3, 2), (3, 3), (5, 4)]
    domains = [((0., 1.), (0., 1.)),
               ((-2e12, 6e12), (1e-12, 5e-12)),
               ((0., 2.**-400), (0., 2.**400))]
    count = 0
    for degrees in degree_pairs:
        for mode in range(3):
            for domain in domains:
                coordinate_scale = 2.**([-200, 0, 200][count % 3])
                controls = []
                for index in range((degrees[0] + 1) * (degrees[1] + 1)):
                    point = [rng.randrange(-64, 65) / 8 * coordinate_scale for _ in range(3)]
                    sign = -1 if mode == 1 or (mode == 2 and index % 3 == 0) else 1
                    weight = sign * 2.**[1000, -1000, 0][index % 3]
                    controls.append([*point, weight])
                fractions = [(0., 0.25), (0.25, 0.75), (0.5, 0.375), (1., 0.625)][count % 4]
                parameters = [a * (1 - t) + b * t for (a, b), t in zip(domain, fractions)]
                header = [*domain[0], *domain[1], *parameters]
                result = reference(degrees, domain, parameters, controls)
                print(*degrees, *(bits(x) for x in header), *(bits(x) for c in controls for x in c), *result)
                count += 1
        # Continuation outside the natural parameter domain uses the same
        # Bernstein polynomial, but is routed through the extended API in Rust.
        domain = domains[0]
        parameters = [-0.25, 1.125]
        result = reference(degrees, domain, parameters, controls)
        print(*degrees, *(bits(x) for x in [*domain[0], *domain[1], *parameters]),
              *(bits(x) for c in controls for x in c), *result)
        count += 1
    assert count == 70


if __name__ == "__main__":
    main()
