"""Emit exact scaled-dot fixtures using Python's independent Fraction arithmetic.

No files are changed. Columns are six left operands, six right operands, scale,
and expected result, each encoded as a binary64 hexadecimal bit pattern.
"""
import math
import random
import struct
from fractions import Fraction


def bits(value):
    return struct.unpack(">Q", struct.pack(">d", value))[0]


def cases():
    rng = random.Random(0x5CA1ED)

    def finite():
        raw = rng.getrandbits(64) % (0x7FF << 52)
        return struct.unpack(">d", struct.pack(">Q", raw))[0] * rng.choice([-1, 1])

    # Independent signs, significands, and exponents over the complete range.
    for _ in range(64):
        yield [finite() for _ in range(6)], [finite() for _ in range(6)], finite()

    # Large terms cancel exactly, leaving unrelated small products.
    for _ in range(64):
        a, b, c, d = (finite() for _ in range(4))
        yield [a, -a, b, -b, c, d], [b, b, a, a, d, c], finite()

    # Full-width significands with controlled exponent sums near rounding and
    # range boundaries. Avoid merely comparing infinities in most cases.
    for _ in range(128):
        a_exp = rng.randint(-500, 500)
        b_exp = rng.randint(-500, 500)
        total = rng.choice(
            [-1076, -1075, -1074, -1023, -1022, -1, 0, 1022, 1023, 1024]
        )
        c_exp = total - a_exp - b_exp
        if not -1022 <= c_exp <= 1023:
            a_exp, b_exp, c_exp = 0, total // 2, total - total // 2

        def operand(exponent):
            return math.ldexp(1 + rng.random(), exponent) * rng.choice([-1, 1])

        yield (
            [operand(a_exp) for _ in range(6)],
            [operand(b_exp) for _ in range(6)],
            operand(c_exp),
        )


def main():
    print("# Generated by tools/numerics/generate_scaled_dot_reference.py; do not edit.")
    for left, right, scale in cases():
        exact = sum(
            (Fraction(a) * Fraction(b) for a, b in zip(left, right)), Fraction()
        ) * Fraction(scale)
        try:
            expected = float(exact)
        except OverflowError:
            expected = math.inf if exact > 0 else -math.inf
        print(" ".join(f"{bits(value):016x}" for value in [*left, *right, scale, expected]))


if __name__ == "__main__":
    main()
