#!/usr/bin/env python3
"""Print independently evaluated regular normals; all intermediates are exact.

Bernstein/Fraction evaluation, not Rust de Boor or crossed rounded derivatives.
Only unit-length normalization uses Decimal (100 digits), then one f64 rounding.
"""
from decimal import Decimal, localcontext
from fractions import Fraction as F
import random

from generate_surface_rational_reference import basis, bits


def reference(degrees, domains, parameters, controls):
    widths = [F(b)-F(a) for a, b in domains]
    normalized = [(F(t)-F(a))/w for t, (a, _), w in zip(parameters, domains, widths)]
    jets = []
    for du, dv in ((0, 0), (1, 0), (0, 1)):
        h = [F(0)]*4
        for index, (x, y, z, w) in enumerate(controls):
            coefficient = (basis(degrees[0], index % (degrees[0]+1), normalized[0], widths[0], du)
                           * basis(degrees[1], index // (degrees[0]+1), normalized[1], widths[1], dv))
            for axis, c in enumerate((F(x)*F(w), F(y)*F(w), F(z)*F(w), F(w))):
                h[axis] += coefficient*c
        jets.append(h)
    h, hu, hv = jets
    if not h[3]: return ["pole"]
    a = [(hu[i]*h[3]-h[i]*hu[3])/h[3]**2 for i in range(3)]
    b = [(hv[i]*h[3]-h[i]*hv[3])/h[3]**2 for i in range(3)]
    n = [a[(i+1)%3]*b[(i+2)%3]-a[(i+2)%3]*b[(i+1)%3] for i in range(3)]
    scale = max(map(abs, n))
    if not scale: return ["degenerate"]
    with localcontext() as context:
        context.prec = 100
        n = [v/scale for v in n]
        decimals = [Decimal(v.numerator)/Decimal(v.denominator) for v in n]
        length = sum(v*v for v in decimals).sqrt()
        return [bits(float(v/length)) for v in decimals]


def main():
    print("# Generated by tools/numerics/generate_surface_normal_reference.py")
    print("# du dv u0 u1 v0 v1 u v; row-major x y z w controls; normal, pole, or degenerate")
    rng = random.Random(20260922)
    domains = [((0., 1.), (0., 1.)), ((-1e12, -1e12+4.), (0., 2.**400)),
               ((0., 2.**-400), (0., 2.**-400))]
    def emit(degrees, domain, parameters, controls):
        print(*degrees, *(bits(x) for x in [*domain[0], *domain[1], *parameters]),
              *(bits(x) for cp in controls for x in cp), *reference(degrees, domain, parameters, controls))
    for degrees in ((1, 1), (2, 1), (2, 2), (3, 3), (5, 4)):
        for mode in range(3):
            for sign in (-1., 1.):
                for domain in domains:
                    controls = []
                    for i in range((degrees[0]+1)*(degrees[1]+1)):
                        xyz = [rng.randrange(-32, 33)/8 for _ in range(3)]
                        weight = (1+i % 4) if mode == 0 else ((-1. if i % 3 == 0 else 1.) if mode == 1
                                                            else 2.**[1000, -1000, 0][i % 3])
                        controls.append([*xyz, sign*weight])
                    parameters = [a+(b-a)*t for (a, b), t in zip(domain, (0.25, 0.375))]
                    emit(degrees, domain, parameters, controls)
    a = 2.**53
    emit((1, 1), domains[0], (0., 0.), [[-1., 0., 0., 1.], [a, a, 0., 1.],
                                     [a-1., a, 0., 1.], [2*a, 2*a, 0., 1.]])
    for weights in ((1., 1.), (1., -1.)):
        for constant in (False, True):
            controls = [[*( [3., -4., 5.] if constant else [i+j, 2*(i+j), 3*(i+j)] ), weights[i]]
                        for j in range(2) for i in range(2)]
            emit((1, 1), domains[0], (0.5, 0.25), controls)


if __name__ == "__main__":
    main()
