#!/usr/bin/env python3
"""Print exact curve references using a Fraction basis-function sum, not de Boor."""
from fractions import Fraction as F
from functools import lru_cache
import math
import random
import struct


def bits(value):
    return struct.pack(">d", value).hex()


def rounded(value):
    try:
        return float(value)
    except OverflowError:
        return -math.inf if value < 0 else math.inf


def reference(degree, knots, controls, parameter, side, derivative_scale=F(1)):
    knots = list(map(F, knots))
    t = F(parameter)
    if t == knots[degree]:
        side = "R"
    elif t == knots[len(controls)]:
        side = "L"

    @lru_cache(None)
    def basis(d, i, order):
        if d == 0:
            if order:
                return F(0)
            return F(knots[i] <= t < knots[i + 1] if side == "R"
                     else knots[i] < t <= knots[i + 1])
        left = knots[i + d] - knots[i]
        right = knots[i + d + 1] - knots[i + 1]
        if order:
            return ((d * basis(d - 1, i, order - 1) / left if left else F(0))
                    - (d * basis(d - 1, i + 1, order - 1) / right if right else F(0)))
        return (((t - knots[i]) * basis(d - 1, i, 0) / left if left else F(0))
                + ((knots[i + d + 1] - t) * basis(d - 1, i + 1, 0) / right if right else F(0)))

    homogeneous = []
    for order in range(3):
        h = [F(0)] * 4
        for i, control in enumerate(controls):
            coefficient = basis(degree, i, order) * F(control[3])
            for axis in range(3):
                h[axis] += coefficient * F(control[axis])
            h[3] += coefficient
        homogeneous.append(h)
    h, first, second = homogeneous
    if not h[3]:
        return ["pole"]
    point = [h[i] / h[3] for i in range(3)]
    d = [(first[i] - point[i] * first[3]) / h[3] for i in range(3)]
    dd = [(second[i] - point[i] * second[3] - 2 * d[i] * first[3]) / h[3] for i in range(3)]
    return [bits(rounded(x * derivative_scale**order))
            for order, values in enumerate([point, d, dd]) for x in values]


def emit(degree, knots, controls, parameter, side):
    print(degree, len(controls), side, *(bits(k) for k in knots), bits(parameter),
          *(bits(x) for control in controls for x in control),
          *reference(degree, knots, controls, parameter, side))


def main():
    rng = random.Random(20260921)
    print("# Generated by tools/numerics/generate_curve_rational_reference.py")
    print("# degree count side; count+degree+1 knots; parameter; x y z w controls; point first second, or pole")
    configurations = [(d, "bezier") for d in [1, 2, 3, 5, 8]]
    configurations += [(d, "unclamped") for d in [2, 3, 5]]
    configurations += [(d, kind) for kind in ["split", "multispan"] for d in [2, 5]]
    count = 0
    for degree, kind in configurations:
        if kind == "bezier":
            fractions = [0.] * (degree + 1) + [1.] * (degree + 1)
        elif kind == "unclamped":
            fractions = [(i - degree) / 4 for i in range(2 * degree + 5)]
        elif kind == "split":
            fractions = [0.] * (degree + 1) + [0.5] * (degree + 1) + [1.] * (degree + 1)
        else:
            fractions = [0.] * (degree + 1) + [0.25, 0.625] + [1.] * (degree + 1)
        for mode in range(3):
            for start, end in [(-2e12, 6e12), (0., 2.**-400), (0., 2.**400)]:
                knots = [start * (1 - t) + end * t for t in fractions]
                controls = []
                scale = 2.**[-200, 0, 200][count % 3]
                for i in range(len(knots) - degree - 1):
                    sign = -1 if mode == 1 or (mode == 2 and i % 3 == 0) else 1
                    controls.append([*(rng.randrange(-64, 65) / 8 * scale for _ in range(3)),
                                     sign * 2.**(1000 if i % 2 == 0 else -1000)])
                fraction = 0.5 if kind == "split" else [0., 0.25, 0.5, 0.625, 1 / 3, 1.][count % 6]
                parameter = start * (1 - fraction) + end * fraction
                for side in (["L", "R"] if kind == "split" else ["L" if count % 2 else "R"]):
                    emit(degree, knots, controls, parameter, side)
                    count += 1
    # Equal Bernstein coefficient pairs cancel exactly, including the tiny pair.
    weights = [2.**1000, 2.**-1000, -2.**-1000, -2.**1000]
    emit(3, [0.] * 4 + [1.] * 4, [[float(i), 1., 2., w] for i, w in enumerate(weights)], 0.5, "R")
    count += 1
    assert count == 127


if __name__ == "__main__":
    main()
