#!/usr/bin/env python3
"""Exact Fraction basis sums at parameters that need not fit in binary64."""
from fractions import Fraction as F
import math
import random
from generate_curve_rational_reference import bits, reference


def emit(degree, knots, controls, fraction, span=-1):
    a, b = ((knots[degree], knots[len(controls)]) if span < 0
            else (knots[span], knots[span+1]))
    parameter = F(a) + (F(b)-F(a))*F(fraction)
    result = reference(degree, knots, controls, parameter, "R")[:3]
    print(degree, len(controls), span, *(bits(k) for k in knots), bits(fraction),
          *(bits(x) for c in controls for x in c), *result)


def main():
    print("# Generated by tools/numerics/generate_fractional_curve_reference.py")
    print("# degree count span(-1=whole); knots; fraction; xyzw controls; point or pole")
    rng = random.Random(965253)
    tiny = math.ulp(0.0)
    fractions = [0.125, 1/3, 0.5]
    for degree in [1, 2, 3, 5, 8]:
        for a, b in [(0.0, tiny), (-3*tiny, 0.0)]:
            knots = [a]*(degree+1) + [b]*(degree+1)
            for sign in [1, -1]:
                controls = [[rng.randint(-8, 8), rng.randint(-8, 8), rng.randint(-8, 8),
                             sign * 2.0**rng.randint(-4, 4)] for _ in range(degree+1)]
                for f in fractions:
                    emit(degree, knots, controls, f)
                    emit(degree, knots, controls, f, degree)
    origin = 2.0**52
    for degree in [1, 2, 3, 5]:
        knots = [-1e308] + [origin]*degree + [origin+2]*(degree+1)
        controls = [[i, (-1)**i, i/2, (-1.0)**i] for i in range(degree+1)]
        for f in fractions:
            emit(degree, knots, controls, f)
    knots = [-1e308, origin-1, origin, origin+1, origin+2, origin+3, origin+4]
    controls = [[0, 0, 1, 1], [1, 2, 0, 2], [2, -1, 1, .5], [4, 1, -1, 4]]
    for f in fractions:
        for span in [-1, 2, 3]:
            emit(2, knots, controls, f, span)
    start = 1e308
    end = math.nextafter(start, math.inf)
    knots = [0, 0, start, start, end, end]
    controls = [[0, 0, 0, 1], [1, 0, 0, 1], [10, 0, 0, 1], [12, 0, 0, 1]]
    for f in [0.125, 0.5, math.nextafter(1, 0)]:
        emit(1, knots, controls, f)
        emit(1, knots, controls, f, 3)
    for degree in [1, 2, 3]:
        knots = [0]*(degree+1) + [1.5]*(degree+1)
        controls = [[i*1e300, i*-1e300, 0, 1] for i in range(degree+1)]
        for f in [tiny, 3*tiny]:
            emit(degree, knots, controls, f)
            emit(degree, knots, controls, f, degree)
    for w in [-1., -(1. - 2.0**-50)]:
        emit(1, [0, 0, tiny, tiny], [[0, 0, 0, 1], [1e308, 0, 0, w]], 0.5)
    for a, b in [(0., 1e-300), (1e-300, 2e-300)]:
        for f in [1e-20, 1e-30]:
            for span in [-1, 1]:
                emit(1, [a, a, b, b], [[0, 0, 0, 1], [1e300, 0, 0, 1]], f, span)
    for f in [1/3, math.nextafter(1/3, math.inf)]:
        emit(1, [0, 0, .5, .5, 1.5, 1.5],
             [[0, 0, 0, 1], [1, 0, 0, 1], [10, 0, 0, 1], [12, 0, 0, 1]], f)


    for span in [-1, 1]:
        emit(1, [0, 0, 1.5, 1.5], [[0, 0, 0, 1], [1, 0, 0, -2]], 1/3, span)


if __name__ == "__main__":
    main()
