#!/usr/bin/env python3
"""Exact Fraction basis sums for first derivatives of fractional curve samples.

No production evaluator or engine output is read. Derivatives are scaled in
rational arithmetic before final binary64 rounding, not after native overflow.
"""
from fractions import Fraction as F
import math
import random
from generate_curve_rational_reference import bits, reference
from generate_fractional_curve_reference import cases


def emit(degree, knots, controls, fraction, span=-1):
    a, b = ((knots[degree], knots[len(controls)]) if span < 0
            else (knots[span], knots[span+1]))
    width = F(b) - F(a)
    parameter = F(a) + width * F(fraction)
    side = "L" if fraction == 1 else "R"
    result = reference(degree, knots, controls, parameter, side, derivative_scale=width)[:6]
    print(degree, len(controls), span, *(bits(k) for k in knots), bits(fraction),
          *(bits(x) for c in controls for x in c), *result)


def main():
    print("# Generated by tools/numerics/generate_fractional_derivative_reference.py")
    print("# degree count span(-1=whole); knots; fraction; xyzw controls; point first, or pole")
    cases(emit)
    rng = random.Random(20260921)
    for degree in [1, 2, 3, 5, 8]:
        for a, b in [(0., 1.), (0., 1e-170), (0., 1e170), (-1e308, 1e308)]:
            knots = [a]*(degree+1) + [b]*(degree+1)
            for gauge in [1., -1e-200, 1e200]:
                controls = [[rng.randint(-32, 32), rng.randint(-32, 32), rng.randint(-32, 32),
                             gauge * 2.**rng.randint(-3, 3)] for _ in range(degree+1)]
                for f in [0., 1/7, 1/3, 0.5, 1.]:
                    emit(degree, knots, controls, f)
    # Sided endpoints and exact whole-domain branch choices at a positional jump.
    for f in [0., 1/3, math.nextafter(1/3, math.inf), 0.5, 1.]:
        for span in [-1, 1, 3]:
            emit(1, [0, 0, 1, 1, 3, 3],
                 [[-4, 0, 0, 1], [-2, 0, 0, 1], [2, 0, 0, 1], [8, 0, 0, 1]], f, span)
    # The point is representable even though fractional speed is not.
    emit(1, [0, 0, 1e308, 1e308], [[-1e308, 0, 0, 1], [1e308, 0, 0, 1]], .5)
    # Native speed underflows; the fractional derivative is a nonzero subnormal.
    emit(1, [0, 0, 1e308, 1e308], [[0, 0, 0, 1], [math.ulp(0.), 0, 0, 1]], .75)
    for width in [1., 1.5, 1e170]:
        emit(2, [0, 0, 0, width, width, width],
             [[0, 0, 0, 1], [.5, 0, 0, 1], [-.5, 0, 0, 1]], 1/3)


if __name__ == "__main__":
    main()
